#!/usr/bin/env ruby
require 'sidtool'

raise "Wrong number of input parameters. Expected 1, got #{ARGV.length}" unless ARGV.length == 1
input_file = ARGV[0]

lines = File.read(input_file).lines
STDERR.puts "#{lines.length} lines"

sid = Sidtool::Sid.new

frames, pokes, skipped = 0, 0, 0
lines.each do |line|
  if line =~ /Frame (\d+)/
    sid.finish_frame
    STDERR.puts "At frame #{$1.to_i}"
    Sidtool::STATE.current_frame = $1.to_i
    frames += 1
  elsif line =~ /Poke (\d+)\: (\d+)/
    address, value = $1.to_i, $2.to_i
    sid.poke(address, value)
    pokes += 1
  else
    skipped += 1
  end
end

sid.stop!

STDERR.puts("#{frames} frames, #{pokes} pokes, #{skipped} skipped")

puts '::SYNTHS = ['
Sidtool::STATE.synths
    .each do |synth|
  puts synth.to_a.inspect + ','
end
puts ']'
